### ISSUE TITLE
What is  heat-inserted "

### ISSUE THREAD

**Issue by Virginia9733** [Coen-Lab/chronic-neuropixels#1]
Sorry for the naive question, but what's the details of "heat-inserted"?
[M1 Brass knurled inserts]: To be heat-inserted into the Payload.

What's the recommended temperature, and what's the procedure?

Many thanks!

**Comment by pipcoen** [comment]
No worries! Typically, we use a standard soldering iron and "press" the threaded insert into the hole with the tip of the soldering iron. For temperature, it depends on the material you are using for the print, but a good rule of thumb is to start at a lower temp and increase it. I think* I usually use ~300C.
