### ISSUE TITLE
Expanding probe base width part of NPX 2 design

### ISSUE THREAD

**Issue by atombysx** [Coen-Lab/chronic-neuropixels#12]
Hi,
Thank you for the design. It's very useful!

I want to make the two probes 0.8mm offset to each other, e.g. the coordinates of the centre of the two probes would be AP -3.0, ML 2.0 and AP -5.0, ML 2.8.

So this is quite easy to achieve on the NP2_payload file by changing parameters d4 from 2.05mm to 2.45mm and d6 from 1.9mm to 2.3mm.

But for the NP2_Docking, I'm a bit lost and I'm not very familiar with working on Inventor. I see that the Docking file should change according to the Payload file and I probably need to change EndCone size to allow space for the shanks.

But it keeps returning erorr updating on AnglePlane1, AngleNub1-1, AngleNub1-2, SlicePlane2.

Is the way I approach this not gonna work?

**Comment by pipcoen** [comment]
This is an interesting request, and I can see it being useful for others. Unfortunately, with FENS coming up, I'm unlikely to be able to look into implementing it for now... To clarify, are you trying to just "widen" the payload to give you the room to adjust the probes relative to each other (should be pretty easy) or do you want to actually offset the walls of the payload relative to each other (trickier)

**Comment by atombysx** [comment]
> This is an interesting request, and I can see it being useful for others. Unfortunately, with FENS coming up, I'm unlikely to be able to look into implementing it for now... To clarify, are you trying to just "widen" the payload to give you the room to adjust the probes relative to each other (should be pretty easy) or do you want to actually offset the walls of the payload relative to each other (trickier)


I would say the first one. Currently I just want some room to adjust the probe relative to each other. But the docking also needs to be expanded for the extra room, right?

**Comment by pipcoen** [comment]
Hmmm. Can you try with the most recent version of the files? I just made the same changes as you (d4 from 2.05mm to 2.45mm and d6 from 1.9mm to 2.3mm). I didn't receive any errors and the NP2_Docking updated appropriately.

If you still get the error, can you share the user parameters you are using? 

FYI, I did get an issue updating the "lid" part--but let's solve this contradiction first :)

**Comment by atombysx** [comment]
> Hmmm. Can you try with the most recent version of the files? I just made the same changes as you (d4 from 2.05mm to 2.45mm and d6 from 1.9mm to 2.3mm). I didn't receive any errors and the NP2_Docking updated appropriately.
> 
> If you still get the error, can you share the user parameters you are using?
> 
> FYI, I did get an issue updating the "lid" part--but let's solve this contradiction first :)

Hi, thanks for checking!

I just tried to replicate the same errors from the new github files:

Yes, the docking can change according to changes of d4 and d6 in NP2_payload file.

Before, I didnt know how to make NP2_docking change accordingly without changing parameters in the parameter list. So I changed User Parameters as well.

However, even though changing d4 and d6 works, changing user parameters can still lead to errors like this:
   NP2_Docking.ipt: Errors occurred during update
     AnglePlane1: Could not build this Plane by Offset from Plane
       Missing or invalid face/plane for offset work plane.  Use Redefine Feature to change the work plane definition.
     Sk:AngleNub1: Could not build this Sketch
       Could not find the plane for defining the sketch coordinate system.  Use Redefine Sketch to select a new face.
       Dimension to reference geometry that could not be resolved.  Use Edit Sketch to delete the reference geometry and rebuild the dimension.
     Ex:AngleNub1-1: Could not build this Extrusion
     SlicePlane2: Could not build this Plane by Line and Angle to Plane
       Zero or multiple solutions for Plane by Line and Angle to Plane.  Use Redefine Feature to change its definition.
         Missing or undefined inputs for Plane by Line and Angle to Plane.  Use Redefine Feature to change its definition.
           Could not attach to edge: edge could not be found.
     Ex:Slice2: Could not build this Extrusion


In my design, I want to change exposed probe length to 4.5 and SliceAngle2 to 10 degrees, but this error keeps happening.

**Comment by pipcoen** [comment]
Hmmmm, I have no problem doing these changes. Here is what I did:

1. Change the params d4 and d6
2. Update the docking file
3. Change the probe exposure to 4.5mm and the angle to 10 degrees.

I didn't get any errors... If this doesn't work for you, can you confirm the version of inventor you are using, and send the exact files you are using here. (To "make" a file update, you need to click the little lightning bolt--you can see the video for an example of this).

**Comment by atombysx** [comment]
> Hmmmm, I have no problem doing these changes. Here is what I did:
> 
> 1. Change the params d4 and d6
> 2. Update the docking file
> 3. Change the probe exposure to 4.5mm and the angle to 10 degrees.
> 
> I didn't get any errors... If this doesn't work for you, can you confirm the version of inventor you are using, and send the exact files you are using here. (To "make" a file update, you need to click the little lightning bolt--you can see the video for an example of this).

Hi, thanks for reminding about the inventor version! I just installed 2023 version and now it worked (it was 2024 before). Sorry for the extra steps of troubleshooting. I will print some prototypes first and will let you know how well it goes.

**Comment by pipcoen** [comment]
Ah, glad that worked! Yes, the versioning with Inventor isn't great :( Closing this issue for now, but please do post your updates in the discussion, and if it works, it would be great to upload modified files to share with the community!
