### ISSUE TITLE
single NP2 probe docking holder

### ISSUE THREAD

**Issue by ChangQing-SH** [Coen-Lab/chronic-neuropixels#16]
Hi  there,

There is a docking holder for a single NP2 probe, and the NP2 docking holder (for 2 probes) is too large for this purpose. 

While the current holder might work, I’m concerned that if it doesn't align properly, it could damage the probe.

Best,
Jon

**Comment by cbimbo** [comment]
Hi,

Thanks for flagging this. We haven't yet made a holder compatible with the 1-probe docking. In the meantime we recommend you use blu tack to fill in the gap between the docking and the holder. By sliding the docking slowly enough into the payload to make sure things align properly it should be ok!

Célian

**Comment by pipcoen** [comment]
@stephenlenzi Perhaps you could comment on this as the primary user of this version of the implant?

**Comment by stephenlenzi** [comment]
The approach I used to assemble was:

1) Assemble the docking part and a payload (without a probe in it) in the assembly apparatus. 
2) Have the dock loose, and the payload fixed firmly.
3) While the dock and empty payload are together, adjust the screws that hold the docking piece until it is well aligned. Make sure the pieces slot together well.
4) Swap out the payload without a probe for one with a probe, and carefully bring the parts together, making sure by eye not to bump into anything.

I haven't designed any extra pieces for this assembly as the need did not arise for me. I think it does require a bit more caution and making sure by eye not to come into contact with the shanks, but I have done many this way without breaking any probes.

**Comment by pipcoen** [comment]
Thanks Steve! I am going to mark this as closed @ChangQing-SH as we don't plant to develop new pieces specifically for this use case, but if you design one personally please upload it! Although it sounds like Steve's solution may be fine already.

**Comment by riccifab** [comment]
Hi @pipcoen @ChangQing-SH  @stephenlenzi  My pull request solve this issue, let me know, we printed it and tested it went pretty smooth, maybe I have to recheck tolerances on the new docker.
