### ISSUE TITLE
Increased Inter-Probe Distance on Apollo Implant Causes Docking Holder Model Failures

### ISSUE THREAD

**Issue by Maxwell-X-Chen** [Coen-Lab/chronic-neuropixels#17]
I set the interprobe distance to 6.5 mm and applied it to all components, but the model crashes when it gets to the docking holder.

`Error Log:
   NP2_DockingHolder.ipt: Errors occurred during update
     Ex:Side2: Problems occurred while building this Extrusion
       The feature as specified did not change the number of faces (and may not have affected the part).  Accept the feature that resulted, or use Edit Sketch or Edit Feature to change the feature definition.
     Fillet:PostHolder1: Could not build this Fillet
       The attempted Fillet operation is too complicated for selected inputs. Try changing the edges, applying the fillet(s) separately or in a different order, else try a face fillet or a different radius.
     Mirror1: Could not build this Mirror
       Execute failure while making this pattern.
         Execute failure while making this pattern.
     Mirror2: Could not build this Mirror
       Execute failure while making this pattern.
         Execute failure while making this pattern.
     Ex:ThreadHole: Problems occurred while building this Extrusion
       The feature as specified did not change the number of faces (and may not have affected the part).  Accept the feature that resulted, or use Edit Sketch or Edit Feature to change the feature definition.
     Chamfer:ThreadInsert: Could not build this Chamfer
       The specified Chamfer distance is too large for selected inputs. Try with a smaller distance.
     Pat:ThreadInsert: Problems occurred while building this Circular Pattern
       One of the features involved in the pattern has associated problems.
         One of the features involved in the pattern has associated problems.`
![Screenshot 2024-10-24 at 12 57 33](https://github.com/user-attachments/assets/d6d3e1be-77dc-4bab-97e3-d330d65a7f72)

**Comment by pipcoen** [comment]
Thanks for raising this @Maxwell-X-Chen! There was an errant parameter that was causing issues at inter-probe distances above 4mm for the holder. I've now fixed this and pushed the change. It seems to work fine, so I'm closing the issue, but let me know if it doesn't!
