### ISSUE TITLE
Increasing exposed probe length after increasing the interprobe distance on Apollo Implant causes build errors

### ISSUE THREAD

**Issue by Maxwell-X-Chen** [Coen-Lab/chronic-neuropixels#20]
![IMG_5415](https://github.com/user-attachments/assets/07914814-425d-492e-8b0c-3973a50bb980)
After increasing the interprobe distance I then tried to change the exposed probe length from the default 5mm to 3.8mm however it throws me this error
```
NP2_Docking. ipt: Errors occurred during update
AnglePlane1: Could not build this Plane by Offset from Plane
Missing or invalid face/plane for offset work plane. Use Redefine Feature to change the work plane definition.
Sk: AngleNub1: Could not build this Sketch
Could not find the plane for defining the sketch coordinate system.
Use Redefine Sketch to select a new face.
Dimension to reference geometry that could not be resolved.
Use Edit Sketch to delete the reference geometry and rebuild the dimension.
SlicePlane2: Could not build this Plane by Line and Angle to Plane Zero or multiple solutions for Plane by Line and Angle to Plane.
Use Redefine Feature to change its definition.
Missing or undefined inputs for Plane by Line and Angle to Plane. Use Redefine Feature to change its definition.
Could not attach to edge: edge could not be found.
```

**Comment by pipcoen** [comment]
Hi Maxwell... Can you confirm all the params you are using, and that you definitely have the latest files? I don't get any error when doing this?

![image](https://github.com/user-attachments/assets/a30bf7d7-e24b-4872-bd34-2749d716dbf4)

**Comment by Maxwell-X-Chen** [comment]
Hi Pip, I redownloaded the latest file, and tried to do this again and still get the same error
![Capture](https://github.com/user-attachments/assets/8569fb85-e606-4393-a5a8-6c82e721008b)

**Comment by Maxwell-X-Chen** [comment]
Hi Pip, I redownloaded the latest file, and tried to do this again and still get the same error...
![Capture](https://github.com/user-attachments/assets/1189ae2d-ebe3-45cc-81be-73b6542e1d4f)

**Comment by Maxwell-X-Chen** [comment]
> Hmmm. I am using the same params without issue... which version of Autodesk are you using?

Autodesk Inventor Professional 2025

**Comment by Maxwell-X-Chen** [comment]
I was able to get around this error by swapping the order or operation somehow. So I increased the exposed probe distance first and then increased the inter probe distance. Thanks for all the help still!

**Comment by pipcoen** [comment]
Ah, okay. For me, the order didn't matter. If you do have a chance to check it on 2023, that would b great to know, just so I can update the info on the main readme.

**Comment by Maxwell-X-Chen** [comment]
Yup, i will update here once i get the 2023 version.
Also i noticed that after the parameter changes. The square things on the side of the docking module all disappeared. is it supposed to happen? 
![image](https://github.com/user-attachments/assets/31cb2a0d-ee40-4967-b8b3-3de553f0c39e)

![image](https://github.com/user-attachments/assets/09a519e6-5ff9-4ca0-821f-4d7de3d99991)

**Comment by pipcoen** [comment]
No, as you can see, they are still there on my version... I'm guessing this is a inventor-version issue... in which case, probably beyond the scope of Coen-support ;)

However, if it doesn't work smoothly with 2023 (I didn't get any errors or warnings at all) please do let me know and we'll get to the bottom of it. Re-opening for now.

**Comment by Maxwell-X-Chen** [comment]
<img width="1458" alt="image" src="https://github.com/user-attachments/assets/b25d5f72-09c5-4f65-ba1a-e1529094f0c6">
Same error in Autodesk Inventor 2023. Retried again with files freshly downloaded from git

**Comment by pipcoen** [comment]
We tracked this down to subtle a versioning issue. Should  be solved now. Please reopen if not!
