### ISSUE TITLE
How to assemble the NP2_SingleProbeMiniature?

### ISSUE THREAD

**Issue by Virginia9733** [Coen-Lab/chronic-neuropixels#6]
Thank you for sharing this wonderful design.

However, I am a bit confused about how to assemble the NP2_SingleProbeMiniature.
Following the instruction, the probe should be attached to the probe side, but it's too narrow for the probe and almost all the shank will be hidden inside the payload and docking.
On the contrary, looks like the head stage side fits the NP2 so well, however, there is no space in the docking for the shanks.

Is it possible to have more clear pictures of the step-by-step ensemble process? Also, it would be great to show how the flex cable is folded when connecting to the headstage. 

Not only for the miniature design, it would be great to have more pictures of how to place the headstage and flex cable using NP1_HeadstageHolder_top & NP2-Alpha_HeadstageHolder_top design.
Thank you so much!

![IMG_7434 (1)](https://github.com/Coen-Lab/chronic-neuropixels/assets/61534754/328a4f1f-2bae-46a3-bc12-8818557aba7e)
![IMG_7435](https://github.com/Coen-Lab/chronic-neuropixels/assets/61534754/fd721597-a1da-49cc-991f-b669bd843820)
![IMG_7437](https://github.com/Coen-Lab/chronic-neuropixels/assets/61534754/1d362709-3bfa-4439-bb44-de7553f4a5db)
![IMG_7432](https://github.com/Coen-Lab/chronic-neuropixels/assets/61534754/dcdc4840-abb4-4ecd-bcf9-d0f0d214784e)
![IMG_7433 (1)](https://github.com/Coen-Lab/chronic-neuropixels/assets/61534754/a3d95ad5-c6b8-4f45-ab7d-807a2c26c0c7)

**Comment by pipcoen** [comment]
@stephenlenzi are you able to help out with this?

**Comment by stephenlenzi** [comment]
That is indeed correct the part shown here is for the most recent commercial 2.0 probes. We do also have a design that fits the NP2-Alpha. I'll add it to the repo either by the end of this week or early next.

**Comment by Virginia9733** [comment]
Thank you so much for all the comments!
My other question is, can we possibly have more pictures about how to attach the head stage to those designs, as well as how to place and connect the flex cable based on the design of NP2_SingleProbeMiniature and NP2-Alpha_HeadstageHolder_top design? This part is also a bit vague to me.

Thank you very much!

**Comment by pipcoen** [comment]
@stephenlenzi thanks! maybe you can upload a couple of extra photos when you are adding the NP2-Alpha version

**Comment by stephenlenzi** [comment]
Yes - a good idea I'll do that

**Comment by Virginia9733** [comment]
![IMG_7551](https://github.com/Coen-Lab/chronic-neuropixels/assets/61534754/f4edea5c-392c-4583-a18f-df60cd8e40d1)
![IMG_7554](https://github.com/Coen-Lab/chronic-neuropixels/assets/61534754/e770f601-e69f-45e5-b21e-cd12b3f699b1)
![IMG_7556](https://github.com/Coen-Lab/chronic-neuropixels/assets/61534754/c6b93b20-054f-48b8-8014-be8450ce1fd4)
![IMG_7557](https://github.com/Coen-Lab/chronic-neuropixels/assets/61534754/ff4e7a09-816a-4452-8ac3-73bc63c2fe68)

Sorry for bombarding messages.
I just tried the implantation using the NPX2 Alpga dummy probe, I have no clue how should I connect the head stage, where should I place it, how should I connect the flex cable, etc., especially if I have two probes.

Many thanks!

**Comment by pipcoen** [comment]
I believe this is the headstage holder from @gomesteixeira? If so, you need to put the headstage in such that the connection point is lined up with the square hole at the top. As written in the instructions, you should be able to check that this fits tightly etc. I believe it only supports attaching a single probe.

**Comment by gomesteixeira** [comment]
Hi all.
@pipcoen is correct that this design only supports a single probe!
Regarding the question you asked, we fold the flex cable into the empty (probe-less) side of the payload module, as much as possible. Only the wider part at the end of the flex cable, where you connect to the headstage, should remain out of the implant. See the pictures attached for reference.
We always test the probe+headstage before implanting, but during the surgery you can only connect the headstage (and mount the headstage holder) after cementing the implant. Make sure you place the holder in the same side as the headstage so you're not straining the flex cable connection.
![implant_schematic](https://github.com/Coen-Lab/chronic-neuropixels/assets/51054568/b7728a9a-ca8c-46e7-a453-963007d0ac36)
![20230704_153122](https://github.com/Coen-Lab/chronic-neuropixels/assets/51054568/45b2d478-e064-4f70-89df-5ee1a80c5e6d)
![20230329_124650](https://github.com/Coen-Lab/chronic-neuropixels/assets/51054568/a60e4147-d4b7-4b0a-83f7-0f72096269ea)
![20230329_124719](https://github.com/Coen-Lab/chronic-neuropixels/assets/51054568/1f2243e1-50e2-4c17-8037-01975c34e271)

**Comment by Virginia9733** [comment]
Thank you very much! Much clearer now! Looking forward to the updated NP2-Alpha version of the SingleProbeMiniature.

**Comment by pipcoen** [comment]
Sorry for the delay @Virginia9733. Steve was very prompt, but I have been away for two weeks. This is now uploaded, and I'm closing this issue, but please re-open it if anything is still unclear.
